CREATE TABLE IF NOT EXISTS Listings (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ItemName TEXT NOT NULL,
  Title TEXT NOT NULL,
  Price DECIMAL(10, 2) NOT NULL,
  Url TEXT NOT NULL,
  ScrapedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BestDeals (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ItemName TEXT NOT NULL,
  Title TEXT NOT NULL,
  Price DECIMAL(10, 2) NOT NULL,
  Url TEXT NOT NULL,
  ScrapedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AveragePriceHistory (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ItemName TEXT NOT NULL,    
  AveragePrice DECIMAL(10, 2) NOT NULL,
  DateCalculated TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TrackedItems (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ItemName TEXT NOT NULL,
  GuildId TEXT NOT NULL,
  AddedAt TEXT NOT NULL
);
